/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package reciclaje;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author USUARIO
 */
public class Analizador extends javax.swing.JFrame {

    /**
     * Creates new form Analizador
     */
        
    
       
        String tamanio;
        int cemento;
        int agregados;
        int ladrilloM;
        int ladrilloP;
        int aceroC;
        int formaleta;
        int perdidacemento;
        int perdidaagregados;
        int perdidaladrilloM;
        int perdidaladrilloP;
        int perdidaaceroC;
        int perdidaformaleta;
        int pcn;
        int pan;
        int plmn;
        int plpn;
        int pacn;
        int pfn;
        int dias;
        int apAlto=800;
        int apAncho=600;
        int x0 = 0;
        int y0 = 0;
        int xN = apAncho-1;
        int yN = apAlto-1;
        double xmin = -10.0;
        double xmax = 10.0;
        double ymin = -1.0;
        double ymax = 1.0;
        int pausar=1;
        int pausarDatosNuevos=1;
        int utilizarbotondegrafico=1;
        String nombre;
        int numeroTiendas;
        double capitalI;
        double valorFactura;
    
    public Analizador() {
        
        try {
            initComponents();
            
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            this.pack();
            this.setVisible(true);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Analizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Analizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Analizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Analizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        jFrame2.setUndecorated(true);
        jFrame2.setSize(640,480);
        
        jFrame2.setLocationRelativeTo(null);
        jFrame2.toFront();
        jFrame2.setVisible(true);
        this.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jFrame2 = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jFrame4 = new javax.swing.JFrame();
        jPan = new javax.swing.JPanel();
        jTextField21 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jTextField25 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel52 = new javax.swing.JLabel();
        jTextField39 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jTextField31 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jTextField33 = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jTextField34 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jTextField35 = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jTextField36 = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jTextField37 = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        jTextField38 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField26 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jTextField41 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jTextField43 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jTextField46 = new javax.swing.JTextField();
        jTextField47 = new javax.swing.JTextField();
        jTextField48 = new javax.swing.JTextField();
        jTextField49 = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jFrame1 = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jFrame3 = new javax.swing.JFrame();
        jLabel15 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jFrame5 = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jFrame6 = new javax.swing.JFrame();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jTextField51 = new javax.swing.JTextField();
        jTextField52 = new javax.swing.JTextField();
        jTextField53 = new javax.swing.JTextField();
        jTextField54 = new javax.swing.JTextField();
        jTextField55 = new javax.swing.JTextField();
        jTextField56 = new javax.swing.JTextField();
        jTextField57 = new javax.swing.JTextField();
        jTextField58 = new javax.swing.JTextField();
        jTextField59 = new javax.swing.JTextField();
        jTextField60 = new javax.swing.JTextField();
        jTextField61 = new javax.swing.JTextField();
        jTextField62 = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        jSeparator25 = new javax.swing.JSeparator();
        jLabel69 = new javax.swing.JLabel();
        jSeparator26 = new javax.swing.JSeparator();
        jLabel70 = new javax.swing.JLabel();
        jSeparator27 = new javax.swing.JSeparator();
        jLabel71 = new javax.swing.JLabel();
        jSeparator28 = new javax.swing.JSeparator();
        jLabel72 = new javax.swing.JLabel();
        jSeparator29 = new javax.swing.JSeparator();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jTextField63 = new javax.swing.JTextField();
        jTextField64 = new javax.swing.JTextField();
        jTextField65 = new javax.swing.JTextField();
        jTextField66 = new javax.swing.JTextField();
        jSeparator30 = new javax.swing.JSeparator();
        jSeparator31 = new javax.swing.JSeparator();
        jTextField67 = new javax.swing.JTextField();
        jLabel75 = new javax.swing.JLabel();
        jTextField68 = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        jSeparator32 = new javax.swing.JSeparator();
        jTextField69 = new javax.swing.JTextField();
        jSeparator33 = new javax.swing.JSeparator();
        jLabel77 = new javax.swing.JLabel();
        jTextField70 = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        jSeparator34 = new javax.swing.JSeparator();
        jTextField71 = new javax.swing.JTextField();
        jLabel79 = new javax.swing.JLabel();
        jTextField72 = new javax.swing.JTextField();
        jTextField73 = new javax.swing.JTextField();
        jTextField74 = new javax.swing.JTextField();
        jTextField75 = new javax.swing.JTextField();
        jSeparator35 = new javax.swing.JSeparator();
        jSeparator36 = new javax.swing.JSeparator();
        jTextField76 = new javax.swing.JTextField();
        jLabel80 = new javax.swing.JLabel();
        jTextField77 = new javax.swing.JTextField();
        jSeparator37 = new javax.swing.JSeparator();
        jTextField78 = new javax.swing.JTextField();
        jTextField79 = new javax.swing.JTextField();
        jTextField80 = new javax.swing.JTextField();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jTextField81 = new javax.swing.JTextField();
        jTextField82 = new javax.swing.JTextField();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jTextField83 = new javax.swing.JTextField();
        jSeparator38 = new javax.swing.JSeparator();
        jLabel85 = new javax.swing.JLabel();
        jTextField84 = new javax.swing.JTextField();
        jTextField85 = new javax.swing.JTextField();
        jTextField86 = new javax.swing.JTextField();
        jSeparator39 = new javax.swing.JSeparator();
        jLabel45 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame2.setAlwaysOnTop(true);
        jFrame2.setFocusableWindowState(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Introduccion.jpg"))); // NOI18N

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jFrame4.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame4.setTitle("Simulador");
        jFrame4.setIconImage(getIconImage());
        jFrame4.setPreferredSize(new java.awt.Dimension(1200, 668));
        jFrame4.setResizable(false);
        jFrame4.getContentPane().setLayout(null);

        jPan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanLayout = new javax.swing.GroupLayout(jPan);
        jPan.setLayout(jPanLayout);
        jPanLayout.setHorizontalGroup(
            jPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );
        jPanLayout.setVerticalGroup(
            jPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );

        jFrame4.getContentPane().add(jPan);
        jPan.setBounds(420, 400, 350, 150);

        jTextField21.setEditable(false);
        jFrame4.getContentPane().add(jTextField21);
        jTextField21.setBounds(580, 70, 180, 20);

        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Agregados");
        jFrame4.getContentPane().add(jLabel47);
        jLabel47.setBounds(510, 110, 80, 14);

        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Cemento");
        jFrame4.getContentPane().add(jLabel46);
        jLabel46.setBounds(510, 70, 70, 14);

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Ladrillo M");
        jFrame4.getContentPane().add(jLabel48);
        jLabel48.setBounds(510, 150, 60, 14);

        jTextField23.setEditable(false);
        jFrame4.getContentPane().add(jTextField23);
        jTextField23.setBounds(580, 150, 180, 20);

        jTextField22.setEditable(false);
        jFrame4.getContentPane().add(jTextField22);
        jTextField22.setBounds(580, 110, 180, 20);

        jTextField24.setEditable(false);
        jFrame4.getContentPane().add(jTextField24);
        jTextField24.setBounds(580, 200, 180, 20);
        jFrame4.getContentPane().add(jSeparator7);
        jSeparator7.setBounds(510, 270, 250, 10);
        jFrame4.getContentPane().add(jSeparator8);
        jSeparator8.setBounds(510, 100, 250, 20);
        jFrame4.getContentPane().add(jSeparator9);
        jSeparator9.setBounds(510, 140, 250, 20);

        jTextField25.setEditable(false);
        jFrame4.getContentPane().add(jTextField25);
        jTextField25.setBounds(580, 280, 180, 20);

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Formaleta");
        jFrame4.getContentPane().add(jLabel49);
        jLabel49.setBounds(510, 280, 60, 14);

        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Datos Iniciales de obra");
        jFrame4.getContentPane().add(jLabel38);
        jLabel38.setBounds(510, 40, 240, 14);

        jTextField19.setEditable(false);
        jTextField19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jFrame4.getContentPane().add(jTextField19);
        jTextField19.setBounds(120, 450, 260, 40);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Día");
        jFrame4.getContentPane().add(jLabel36);
        jLabel36.setBounds(80, 460, 110, 15);

        jLabel40.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFrame4.getContentPane().add(jLabel40);
        jLabel40.setBounds(40, 390, 750, 170);

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Ladrillo P");
        jFrame4.getContentPane().add(jLabel50);
        jLabel50.setBounds(510, 200, 60, 14);

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Acero");
        jFrame4.getContentPane().add(jLabel51);
        jLabel51.setBounds(510, 240, 60, 14);

        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Datos Proyectados");
        jFrame4.getContentPane().add(jLabel39);
        jLabel39.setBounds(830, 40, 150, 14);
        jFrame4.getContentPane().add(jSeparator13);
        jSeparator13.setBounds(820, 590, 340, 10);

        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Cemento");
        jFrame4.getContentPane().add(jLabel52);
        jLabel52.setBounds(810, 70, 70, 14);

        jTextField39.setEditable(false);
        jFrame4.getContentPane().add(jTextField39);
        jTextField39.setBounds(1020, 600, 130, 20);

        jTextField27.setEditable(false);
        jFrame4.getContentPane().add(jTextField27);
        jTextField27.setBounds(880, 70, 130, 20);

        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Agregados");
        jFrame4.getContentPane().add(jLabel53);
        jLabel53.setBounds(810, 110, 80, 14);

        jTextField28.setEditable(false);
        jFrame4.getContentPane().add(jTextField28);
        jTextField28.setBounds(880, 110, 130, 20);

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Ladrillo M");
        jFrame4.getContentPane().add(jLabel54);
        jLabel54.setBounds(810, 150, 60, 14);

        jTextField29.setEditable(false);
        jFrame4.getContentPane().add(jTextField29);
        jTextField29.setBounds(880, 150, 130, 20);

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Ladrillo P");
        jFrame4.getContentPane().add(jLabel55);
        jLabel55.setBounds(810, 200, 60, 14);

        jTextField30.setEditable(false);
        jFrame4.getContentPane().add(jTextField30);
        jTextField30.setBounds(880, 200, 130, 20);

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Acero");
        jFrame4.getContentPane().add(jLabel56);
        jLabel56.setBounds(810, 240, 60, 14);

        jTextField31.setEditable(false);
        jFrame4.getContentPane().add(jTextField31);
        jTextField31.setBounds(880, 240, 130, 20);

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Formaleta");
        jFrame4.getContentPane().add(jLabel57);
        jLabel57.setBounds(810, 280, 60, 14);

        jTextField32.setEditable(false);
        jFrame4.getContentPane().add(jTextField32);
        jTextField32.setBounds(880, 280, 130, 20);

        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Perdidas Calculadas inicialmente");
        jFrame4.getContentPane().add(jLabel42);
        jLabel42.setBounds(820, 360, 170, 14);

        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("Cemento");
        jFrame4.getContentPane().add(jLabel58);
        jLabel58.setBounds(810, 390, 70, 14);

        jTextField33.setEditable(false);
        jFrame4.getContentPane().add(jTextField33);
        jTextField33.setBounds(880, 390, 130, 20);

        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Agregados");
        jFrame4.getContentPane().add(jLabel59);
        jLabel59.setBounds(810, 430, 80, 14);

        jTextField34.setEditable(false);
        jFrame4.getContentPane().add(jTextField34);
        jTextField34.setBounds(880, 430, 130, 20);

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Ladrillo M");
        jFrame4.getContentPane().add(jLabel60);
        jLabel60.setBounds(810, 470, 60, 14);

        jTextField35.setEditable(false);
        jFrame4.getContentPane().add(jTextField35);
        jTextField35.setBounds(880, 470, 130, 20);

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("Ladrillo P");
        jFrame4.getContentPane().add(jLabel61);
        jLabel61.setBounds(810, 520, 60, 14);

        jTextField36.setEditable(false);
        jFrame4.getContentPane().add(jTextField36);
        jTextField36.setBounds(880, 520, 130, 20);

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("Acero");
        jFrame4.getContentPane().add(jLabel62);
        jLabel62.setBounds(810, 560, 60, 14);

        jTextField37.setEditable(false);
        jFrame4.getContentPane().add(jTextField37);
        jTextField37.setBounds(880, 560, 130, 20);

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("Formaleta");
        jFrame4.getContentPane().add(jLabel63);
        jLabel63.setBounds(810, 600, 60, 14);

        jTextField38.setEditable(false);
        jFrame4.getContentPane().add(jTextField38);
        jTextField38.setBounds(880, 600, 130, 20);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Porcentajes");
        jFrame4.getContentPane().add(jLabel9);
        jLabel9.setBounds(1020, 40, 90, 14);

        jLabel43.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFrame4.getContentPane().add(jLabel43);
        jLabel43.setBounds(800, 350, 380, 290);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "X1", "X2", "X3", "X4", "X5", "X6"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jFrame4.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 50, 454, 270);

        jTextField26.setEditable(false);
        jFrame4.getContentPane().add(jTextField26);
        jTextField26.setBounds(580, 240, 180, 20);
        jFrame4.getContentPane().add(jSeparator5);
        jSeparator5.setBounds(20, 30, 450, 20);
        jFrame4.getContentPane().add(jSeparator6);
        jSeparator6.setBounds(510, 60, 250, 20);
        jFrame4.getContentPane().add(jSeparator10);
        jSeparator10.setBounds(510, 230, 250, 20);
        jFrame4.getContentPane().add(jSeparator11);
        jSeparator11.setBounds(510, 190, 250, 0);
        jFrame4.getContentPane().add(jSeparator12);
        jSeparator12.setBounds(510, 190, 250, 20);
        jFrame4.getContentPane().add(jSeparator14);
        jSeparator14.setBounds(820, 60, 340, 10);
        jFrame4.getContentPane().add(jSeparator15);
        jSeparator15.setBounds(820, 100, 340, 10);
        jFrame4.getContentPane().add(jSeparator16);
        jSeparator16.setBounds(820, 140, 340, 10);
        jFrame4.getContentPane().add(jSeparator17);
        jSeparator17.setBounds(820, 180, 340, 10);
        jFrame4.getContentPane().add(jSeparator18);
        jSeparator18.setBounds(820, 230, 340, 10);

        jTextField41.setEditable(false);
        jFrame4.getContentPane().add(jTextField41);
        jTextField41.setBounds(1020, 110, 130, 20);

        jTextField40.setEditable(false);
        jFrame4.getContentPane().add(jTextField40);
        jTextField40.setBounds(1020, 70, 130, 20);

        jTextField42.setEditable(false);
        jFrame4.getContentPane().add(jTextField42);
        jTextField42.setBounds(1020, 150, 130, 20);

        jTextField43.setEditable(false);
        jFrame4.getContentPane().add(jTextField43);
        jTextField43.setBounds(1020, 200, 130, 20);

        jTextField44.setEditable(false);
        jFrame4.getContentPane().add(jTextField44);
        jTextField44.setBounds(1020, 240, 130, 20);

        jTextField45.setEditable(false);
        jFrame4.getContentPane().add(jTextField45);
        jTextField45.setBounds(1020, 280, 130, 20);

        jTextField46.setEditable(false);
        jFrame4.getContentPane().add(jTextField46);
        jTextField46.setBounds(1020, 390, 130, 20);

        jTextField47.setEditable(false);
        jFrame4.getContentPane().add(jTextField47);
        jTextField47.setBounds(1020, 430, 130, 20);

        jTextField48.setEditable(false);
        jFrame4.getContentPane().add(jTextField48);
        jTextField48.setBounds(1020, 470, 130, 20);

        jTextField49.setEditable(false);
        jFrame4.getContentPane().add(jTextField49);
        jTextField49.setBounds(1020, 520, 130, 20);

        jTextField50.setEditable(false);
        jFrame4.getContentPane().add(jTextField50);
        jTextField50.setBounds(1020, 560, 130, 20);
        jFrame4.getContentPane().add(jSeparator19);
        jSeparator19.setBounds(820, 270, 340, 10);
        jFrame4.getContentPane().add(jSeparator20);
        jSeparator20.setBounds(820, 380, 340, 10);
        jFrame4.getContentPane().add(jSeparator21);
        jSeparator21.setBounds(820, 420, 340, 10);
        jFrame4.getContentPane().add(jSeparator22);
        jSeparator22.setBounds(820, 460, 340, 10);
        jFrame4.getContentPane().add(jSeparator23);
        jSeparator23.setBounds(820, 500, 340, 10);
        jFrame4.getContentPane().add(jSeparator24);
        jSeparator24.setBounds(820, 550, 340, 10);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Porcentajes");
        jFrame4.getContentPane().add(jLabel8);
        jLabel8.setBounds(1020, 360, 90, 14);

        jLabel41.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFrame4.getContentPane().add(jLabel41);
        jLabel41.setBounds(800, 30, 380, 290);

        jLabel37.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFrame4.getContentPane().add(jLabel37);
        jLabel37.setBounds(500, 30, 270, 290);

        jButton3.setText("VER GRAFICO AHORRO MATERIALES");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jFrame4.getContentPane().add(jButton3);
        jButton3.setBounds(480, 590, 220, 40);

        jButton4.setText("PAUSAR");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jFrame4.getContentPane().add(jButton4);
        jButton4.setBounds(200, 590, 150, 40);

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Tabla de datos");
        jFrame4.getContentPane().add(jLabel34);
        jLabel34.setBounds(20, 10, 310, 14);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        jFrame4.getContentPane().add(jLabel32);
        jLabel32.setBounds(0, 0, 1200, 670);

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setTitle("Selección de tamaño");
        jFrame1.setIconImage(getIconImage());
        jFrame1.setResizable(false);
        jFrame1.getContentPane().setLayout(null);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Seleccione el tamaño de su obra:");
        jFrame1.getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 20, 430, 20);
        jFrame1.getContentPane().add(jSeparator2);
        jSeparator2.setBounds(20, 40, 590, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("PEQUEÑAS");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jButton1);
        jButton1.setBounds(40, 320, 150, 40);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("GRANDES");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jButton5);
        jButton5.setBounds(460, 320, 150, 40);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setText("MEDIANAS");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jButton6);
        jButton6.setBounds(250, 320, 150, 40);

        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFrame1.getContentPane().add(jLabel1);
        jLabel1.setBounds(440, 100, 190, 190);

        jLabel3.setText("jLabel1");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFrame1.getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 100, 190, 190);

        jLabel4.setText("jLabel1");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFrame1.getContentPane().add(jLabel4);
        jLabel4.setBounds(230, 100, 190, 190);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo1.jpg"))); // NOI18N
        jFrame1.getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 640, 480);

        jFrame3.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame3.setTitle("Datos de la obra");
        jFrame3.setIconImage(getIconImage());
        jFrame3.setResizable(false);
        jFrame3.getContentPane().setLayout(null);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Ingrese los datos de la obra:");
        jFrame3.getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 20, 430, 14);
        jFrame3.getContentPane().add(jTextField9);
        jTextField9.setBounds(30, 170, 140, 20);

        jTextField15.setEditable(false);
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jFrame3.getContentPane().add(jTextField15);
        jTextField15.setBounds(30, 80, 160, 20);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Cemento (En kg)");
        jFrame3.getContentPane().add(jLabel22);
        jLabel22.setBounds(30, 150, 100, 15);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("TIPO DE OBRA:");
        jFrame3.getContentPane().add(jLabel21);
        jLabel21.setBounds(30, 60, 110, 15);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("CONTINUAR");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jFrame3.getContentPane().add(jButton2);
        jButton2.setBounds(260, 400, 150, 40);
        jFrame3.getContentPane().add(jSeparator4);
        jSeparator4.setBounds(20, 40, 590, 20);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Agregados (En kg)");
        jFrame3.getContentPane().add(jLabel23);
        jLabel23.setBounds(30, 210, 120, 15);
        jFrame3.getContentPane().add(jTextField10);
        jTextField10.setBounds(30, 230, 140, 20);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Ladrillo macizo");
        jFrame3.getContentPane().add(jLabel24);
        jLabel24.setBounds(260, 150, 100, 15);
        jFrame3.getContentPane().add(jTextField11);
        jTextField11.setBounds(260, 170, 140, 20);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Ladrillo perforado");
        jFrame3.getContentPane().add(jLabel25);
        jLabel25.setBounds(260, 210, 100, 15);
        jFrame3.getContentPane().add(jTextField12);
        jTextField12.setBounds(260, 230, 140, 20);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Acerro corrugado");
        jFrame3.getContentPane().add(jLabel26);
        jLabel26.setBounds(460, 150, 100, 15);
        jFrame3.getContentPane().add(jTextField13);
        jTextField13.setBounds(460, 170, 140, 20);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Formaleta");
        jFrame3.getContentPane().add(jLabel27);
        jLabel27.setBounds(460, 210, 100, 15);
        jFrame3.getContentPane().add(jTextField14);
        jTextField14.setBounds(460, 230, 140, 20);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Días estimados");
        jFrame3.getContentPane().add(jLabel28);
        jLabel28.setBounds(260, 300, 100, 15);
        jFrame3.getContentPane().add(jTextField16);
        jTextField16.setBounds(260, 320, 140, 20);

        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFrame3.getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 130, 610, 230);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo1.jpg"))); // NOI18N
        jFrame3.getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 0, 640, 480);

        jFrame5.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame5.setAlwaysOnTop(true);
        jFrame5.setFocusableWindowState(false);
        jFrame5.getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jFrame5.getContentPane().add(jLabel6);
        jLabel6.setBounds(280, 240, 160, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cargando.jpg"))); // NOI18N
        jFrame5.getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 600, 400);

        jFrame6.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame6.setTitle("Resultados");
        jFrame6.setAlwaysOnTop(true);
        jFrame6.setIconImage(getIconImage());
        jFrame6.setPreferredSize(new java.awt.Dimension(1200, 330));
        jFrame6.setResizable(false);
        jFrame6.getContentPane().setLayout(null);

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Porcentajes");
        jFrame6.getContentPane().add(jLabel17);
        jLabel17.setBounds(290, 30, 90, 14);

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Porcentajes");
        jFrame6.getContentPane().add(jLabel16);
        jLabel16.setBounds(660, 30, 90, 14);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Porcentajes");
        jFrame6.getContentPane().add(jLabel12);
        jLabel12.setBounds(1040, 30, 90, 14);

        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("Elementos Reciclados");
        jFrame6.getContentPane().add(jLabel67);
        jLabel67.setBounds(810, 30, 210, 14);

        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("Perdidas Calculadas usando Reciclaje");
        jFrame6.getContentPane().add(jLabel65);
        jLabel65.setBounds(420, 30, 210, 14);

        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("Perdidas Calculadas inicialmente");
        jFrame6.getContentPane().add(jLabel66);
        jLabel66.setBounds(30, 30, 210, 14);

        jTextField51.setEditable(false);
        jFrame6.getContentPane().add(jTextField51);
        jTextField51.setBounds(1030, 270, 130, 20);

        jTextField52.setEditable(false);
        jFrame6.getContentPane().add(jTextField52);
        jTextField52.setBounds(890, 270, 130, 20);

        jTextField53.setEditable(false);
        jFrame6.getContentPane().add(jTextField53);
        jTextField53.setBounds(890, 230, 130, 20);

        jTextField54.setEditable(false);
        jFrame6.getContentPane().add(jTextField54);
        jTextField54.setBounds(1030, 230, 130, 20);

        jTextField55.setEditable(false);
        jFrame6.getContentPane().add(jTextField55);
        jTextField55.setBounds(890, 190, 130, 20);

        jTextField56.setEditable(false);
        jFrame6.getContentPane().add(jTextField56);
        jTextField56.setBounds(1030, 190, 130, 20);

        jTextField57.setEditable(false);
        jFrame6.getContentPane().add(jTextField57);
        jTextField57.setBounds(890, 140, 130, 20);

        jTextField58.setEditable(false);
        jFrame6.getContentPane().add(jTextField58);
        jTextField58.setBounds(1030, 140, 130, 20);

        jTextField59.setEditable(false);
        jFrame6.getContentPane().add(jTextField59);
        jTextField59.setBounds(890, 100, 130, 20);

        jTextField60.setEditable(false);
        jFrame6.getContentPane().add(jTextField60);
        jTextField60.setBounds(1030, 100, 130, 20);

        jTextField61.setEditable(false);
        jFrame6.getContentPane().add(jTextField61);
        jTextField61.setBounds(1030, 60, 130, 20);

        jTextField62.setEditable(false);
        jFrame6.getContentPane().add(jTextField62);
        jTextField62.setBounds(890, 60, 130, 20);

        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Cemento");
        jFrame6.getContentPane().add(jLabel68);
        jLabel68.setBounds(820, 60, 70, 14);
        jFrame6.getContentPane().add(jSeparator25);
        jSeparator25.setBounds(830, 90, 340, 10);

        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("Agregados");
        jFrame6.getContentPane().add(jLabel69);
        jLabel69.setBounds(820, 100, 80, 14);
        jFrame6.getContentPane().add(jSeparator26);
        jSeparator26.setBounds(830, 130, 340, 10);

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("Ladrillo M");
        jFrame6.getContentPane().add(jLabel70);
        jLabel70.setBounds(820, 140, 60, 14);
        jFrame6.getContentPane().add(jSeparator27);
        jSeparator27.setBounds(830, 170, 340, 10);

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Ladrillo P");
        jFrame6.getContentPane().add(jLabel71);
        jLabel71.setBounds(820, 190, 60, 14);
        jFrame6.getContentPane().add(jSeparator28);
        jSeparator28.setBounds(830, 220, 340, 10);

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("Acero");
        jFrame6.getContentPane().add(jLabel72);
        jLabel72.setBounds(820, 230, 60, 14);
        jFrame6.getContentPane().add(jSeparator29);
        jSeparator29.setBounds(830, 260, 340, 10);

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("Formaleta");
        jFrame6.getContentPane().add(jLabel73);
        jLabel73.setBounds(820, 270, 60, 14);

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("Ladrillo M");
        jFrame6.getContentPane().add(jLabel74);
        jLabel74.setBounds(430, 140, 60, 14);

        jTextField63.setEditable(false);
        jFrame6.getContentPane().add(jTextField63);
        jTextField63.setBounds(500, 190, 130, 20);

        jTextField64.setEditable(false);
        jFrame6.getContentPane().add(jTextField64);
        jTextField64.setBounds(500, 60, 130, 20);

        jTextField65.setEditable(false);
        jFrame6.getContentPane().add(jTextField65);
        jTextField65.setBounds(640, 190, 130, 20);

        jTextField66.setEditable(false);
        jFrame6.getContentPane().add(jTextField66);
        jTextField66.setBounds(640, 270, 130, 20);
        jFrame6.getContentPane().add(jSeparator30);
        jSeparator30.setBounds(440, 220, 340, 10);
        jFrame6.getContentPane().add(jSeparator31);
        jSeparator31.setBounds(440, 170, 340, 10);

        jTextField67.setEditable(false);
        jFrame6.getContentPane().add(jTextField67);
        jTextField67.setBounds(640, 230, 130, 20);

        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("Cemento");
        jFrame6.getContentPane().add(jLabel75);
        jLabel75.setBounds(430, 60, 70, 14);

        jTextField68.setEditable(false);
        jFrame6.getContentPane().add(jTextField68);
        jTextField68.setBounds(500, 100, 130, 20);

        jLabel76.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(255, 255, 255));
        jLabel76.setText("Formaleta");
        jFrame6.getContentPane().add(jLabel76);
        jLabel76.setBounds(430, 270, 60, 14);
        jFrame6.getContentPane().add(jSeparator32);
        jSeparator32.setBounds(440, 130, 340, 10);

        jTextField69.setEditable(false);
        jFrame6.getContentPane().add(jTextField69);
        jTextField69.setBounds(500, 230, 130, 20);
        jFrame6.getContentPane().add(jSeparator33);
        jSeparator33.setBounds(440, 90, 340, 10);

        jLabel77.setForeground(new java.awt.Color(255, 255, 255));
        jLabel77.setText("Agregados");
        jFrame6.getContentPane().add(jLabel77);
        jLabel77.setBounds(430, 100, 80, 14);

        jTextField70.setEditable(false);
        jFrame6.getContentPane().add(jTextField70);
        jTextField70.setBounds(500, 270, 130, 20);

        jLabel78.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(255, 255, 255));
        jLabel78.setText("Acero");
        jFrame6.getContentPane().add(jLabel78);
        jLabel78.setBounds(430, 230, 60, 14);
        jFrame6.getContentPane().add(jSeparator34);
        jSeparator34.setBounds(440, 260, 340, 10);

        jTextField71.setEditable(false);
        jFrame6.getContentPane().add(jTextField71);
        jTextField71.setBounds(640, 140, 130, 20);

        jLabel79.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(255, 255, 255));
        jLabel79.setText("Ladrillo P");
        jFrame6.getContentPane().add(jLabel79);
        jLabel79.setBounds(430, 190, 60, 14);

        jTextField72.setEditable(false);
        jFrame6.getContentPane().add(jTextField72);
        jTextField72.setBounds(640, 60, 130, 20);

        jTextField73.setEditable(false);
        jFrame6.getContentPane().add(jTextField73);
        jTextField73.setBounds(640, 100, 130, 20);

        jTextField74.setEditable(false);
        jFrame6.getContentPane().add(jTextField74);
        jTextField74.setBounds(500, 140, 130, 20);

        jTextField75.setEditable(false);
        jFrame6.getContentPane().add(jTextField75);
        jTextField75.setBounds(110, 270, 130, 20);
        jFrame6.getContentPane().add(jSeparator35);
        jSeparator35.setBounds(50, 130, 340, 10);
        jFrame6.getContentPane().add(jSeparator36);
        jSeparator36.setBounds(50, 90, 340, 10);

        jTextField76.setEditable(false);
        jFrame6.getContentPane().add(jTextField76);
        jTextField76.setBounds(250, 230, 130, 20);

        jLabel80.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setText("Ladrillo M");
        jFrame6.getContentPane().add(jLabel80);
        jLabel80.setBounds(40, 140, 60, 14);

        jTextField77.setEditable(false);
        jFrame6.getContentPane().add(jTextField77);
        jTextField77.setBounds(250, 60, 130, 20);
        jFrame6.getContentPane().add(jSeparator37);
        jSeparator37.setBounds(50, 220, 340, 10);

        jTextField78.setEditable(false);
        jFrame6.getContentPane().add(jTextField78);
        jTextField78.setBounds(250, 190, 130, 20);

        jTextField79.setEditable(false);
        jFrame6.getContentPane().add(jTextField79);
        jTextField79.setBounds(250, 140, 130, 20);

        jTextField80.setEditable(false);
        jFrame6.getContentPane().add(jTextField80);
        jTextField80.setBounds(110, 190, 130, 20);

        jLabel81.setForeground(new java.awt.Color(255, 255, 255));
        jLabel81.setText("Cemento");
        jFrame6.getContentPane().add(jLabel81);
        jLabel81.setBounds(40, 60, 70, 14);

        jLabel82.setForeground(new java.awt.Color(255, 255, 255));
        jLabel82.setText("Agregados");
        jFrame6.getContentPane().add(jLabel82);
        jLabel82.setBounds(40, 100, 80, 14);

        jTextField81.setEditable(false);
        jFrame6.getContentPane().add(jTextField81);
        jTextField81.setBounds(110, 100, 130, 20);

        jTextField82.setEditable(false);
        jFrame6.getContentPane().add(jTextField82);
        jTextField82.setBounds(110, 140, 130, 20);

        jLabel83.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(255, 255, 255));
        jLabel83.setText("Formaleta");
        jFrame6.getContentPane().add(jLabel83);
        jLabel83.setBounds(40, 270, 60, 14);

        jLabel84.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(255, 255, 255));
        jLabel84.setText("Ladrillo P");
        jFrame6.getContentPane().add(jLabel84);
        jLabel84.setBounds(40, 190, 60, 14);

        jTextField83.setEditable(false);
        jFrame6.getContentPane().add(jTextField83);
        jTextField83.setBounds(110, 230, 130, 20);
        jFrame6.getContentPane().add(jSeparator38);
        jSeparator38.setBounds(50, 260, 340, 10);

        jLabel85.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(255, 255, 255));
        jLabel85.setText("Acero");
        jFrame6.getContentPane().add(jLabel85);
        jLabel85.setBounds(40, 230, 60, 14);

        jTextField84.setEditable(false);
        jFrame6.getContentPane().add(jTextField84);
        jTextField84.setBounds(110, 60, 130, 20);

        jTextField85.setEditable(false);
        jFrame6.getContentPane().add(jTextField85);
        jTextField85.setBounds(250, 270, 130, 20);

        jTextField86.setEditable(false);
        jFrame6.getContentPane().add(jTextField86);
        jTextField86.setBounds(250, 100, 130, 20);
        jFrame6.getContentPane().add(jSeparator39);
        jSeparator39.setBounds(50, 170, 340, 10);

        jLabel45.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFrame6.getContentPane().add(jLabel45);
        jLabel45.setBounds(800, 20, 380, 290);

        jLabel44.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFrame6.getContentPane().add(jLabel44);
        jLabel44.setBounds(20, 20, 380, 290);

        jLabel64.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFrame6.getContentPane().add(jLabel64);
        jLabel64.setBounds(410, 20, 380, 290);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoresultados.jpg"))); // NOI18N
        jFrame6.getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 1200, 330);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 480));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("true"), this, org.jdesktop.beansbinding.BeanProperty.create("undecorated"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jFrame1.setVisible(false);
        jFrame3.setSize(640,480);     
        jFrame3.setLocationRelativeTo(null);
        jFrame3.toFront();
        jFrame3.setVisible(true);
        tamanio="PEQUEÑA";
        //pausarDatosNuevos=0;
        colocarDatosCompetencia();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jFrame3.setVisible(false);
        cemento=Integer.parseInt(jTextField9.getText());
        agregados=Integer.parseInt(jTextField10.getText());
        ladrilloM=Integer.parseInt(jTextField11.getText());
        ladrilloP=Integer.parseInt(jTextField12.getText());
        aceroC=Integer.parseInt(jTextField13.getText());
        formaleta=Integer.parseInt(jTextField14.getText());
        dias=Integer.parseInt(jTextField16.getText());
        
        pantallaCarga();
        
        
        
        pausarDatosNuevos=0;
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(pausar==0){
            utilizarbotondegrafico=0;
            pausar=1;
            jButton4.setText("CONTINUAR");
            jButton3.setEnabled(true);
        }else{
            if(pausar==1){
                pausar=0;
                jButton4.setText("PAUSAR");
                jButton3.setEnabled(false);
                jPan.removeAll();
                jPan.repaint();
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        Graphics2D gfx = (Graphics2D)jPan.getGraphics();
        
        
        
        if(utilizarbotondegrafico==0){
            
                int datoinicio=0;
                
                for(int j=0;j<Reciclaje.valoresT.size()-1;j++){
                    System.out.println(Reciclaje.valoresT.get(j));
                    gfx.drawLine(j,(Reciclaje.valoresT.get(j).intValue()),j+1,(Reciclaje.valoresT.get(j+1).intValue()));
                }
            
        }
        utilizarbotondegrafico=1;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jFrame1.setVisible(false);
        jFrame3.setSize(640,480);     
        jFrame3.setLocationRelativeTo(null);
        jFrame3.toFront();
        jFrame3.setVisible(true);
        tamanio="GRANDE";
        //pausarDatosNuevos=0;
        colocarDatosCompetencia();    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jFrame1.setVisible(false);
        jFrame3.setSize(640,480);     
        jFrame3.setLocationRelativeTo(null);
        jFrame3.toFront();
        jFrame3.setVisible(true);
        tamanio="MEDIANA";
        //pausarDatosNuevos=0;
        colocarDatosCompetencia();
    }//GEN-LAST:event_jButton6ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JFrame jFrame5;
    private javax.swing.JFrame jFrame6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator36;
    private javax.swing.JSeparator jSeparator37;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JSeparator jSeparator39;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    private javax.swing.JTextField jTextField55;
    private javax.swing.JTextField jTextField56;
    private javax.swing.JTextField jTextField57;
    private javax.swing.JTextField jTextField58;
    private javax.swing.JTextField jTextField59;
    private javax.swing.JTextField jTextField60;
    private javax.swing.JTextField jTextField61;
    private javax.swing.JTextField jTextField62;
    private javax.swing.JTextField jTextField63;
    private javax.swing.JTextField jTextField64;
    private javax.swing.JTextField jTextField65;
    private javax.swing.JTextField jTextField66;
    private javax.swing.JTextField jTextField67;
    private javax.swing.JTextField jTextField68;
    private javax.swing.JTextField jTextField69;
    private javax.swing.JTextField jTextField70;
    private javax.swing.JTextField jTextField71;
    private javax.swing.JTextField jTextField72;
    private javax.swing.JTextField jTextField73;
    private javax.swing.JTextField jTextField74;
    private javax.swing.JTextField jTextField75;
    private javax.swing.JTextField jTextField76;
    private javax.swing.JTextField jTextField77;
    private javax.swing.JTextField jTextField78;
    private javax.swing.JTextField jTextField79;
    private javax.swing.JTextField jTextField80;
    private javax.swing.JTextField jTextField81;
    private javax.swing.JTextField jTextField82;
    private javax.swing.JTextField jTextField83;
    private javax.swing.JTextField jTextField84;
    private javax.swing.JTextField jTextField85;
    private javax.swing.JTextField jTextField86;
    private javax.swing.JTextField jTextField9;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public static void pause() {
        try {
            Thread.sleep(5000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Analizador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public static void pause1() {
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Analizador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
     public static void pause2() {
        try {
            Thread.sleep(20000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Analizador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void iniciarDatos(){
        pause();
        jFrame2.setVisible(false);
   
        jFrame1.setSize(640,480);     
        jFrame1.setLocationRelativeTo(null);
        jFrame1.toFront();
        jFrame1.setVisible(true);
        javax.swing.ImageIcon image = new javax.swing.ImageIcon(getClass().getResource("/img/pequeña.jpg"));
        jLabel3.setIcon(new javax.swing.ImageIcon(image.getImage().getScaledInstance(190, 190, 190)));
        javax.swing.ImageIcon image1 = new javax.swing.ImageIcon(getClass().getResource("/img/medianas.jpg"));
        jLabel4.setIcon(new javax.swing.ImageIcon(image1.getImage().getScaledInstance(190, 190, 190)));
        javax.swing.ImageIcon image2 = new javax.swing.ImageIcon(getClass().getResource("/img/grandes.jpg"));
        jLabel1.setIcon(new javax.swing.ImageIcon(image2.getImage().getScaledInstance(190, 190, 190)));
        
        this.setVisible(false);
}

@Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("img/220px-UN_logotipo.png"));


        return retValue;
    }

    public void colocarGeneraciones(String text){
        jTextField19.setText(text);
        pause1();
    }
    
    public void continuar(){
        while(pausar==1){
            pause1();
        }
    }
    
    public void continuarDatosNuevos(){
        while(pausarDatosNuevos==1){
            pause1();
        }
    }
    
    public void colocarDatosCompetencia(){
        jTextField15.setText(tamanio);
        jTextField15.setEditable(false);
        
        
        
        
        
    }
    
    public void pintar(){
        Graphics2D gfx = (Graphics2D)jPan.getGraphics();
        gfx.drawLine(0, 0, 100, 100);
    }
    
    public void pantallaCarga(){
        jFrame5.setUndecorated(true);
        jFrame5.setSize(600,400);     
        jFrame5.setLocationRelativeTo(null);
        jFrame5.toFront();
        jFrame5.setVisible(true);
        jLabel6.setText(tamanio);
        
        
        
    }
    
    public void cerrarCarga(){
        System.out.println("cerrando");
        pause();
        jFrame5.setVisible(false);
        jFrame4.setSize(1200,668);     
        jFrame4.setLocationRelativeTo(null);
        jFrame4.setVisible(true);
        
        jTextField21.setText(String.valueOf(cemento));
        jTextField22.setText(String.valueOf(agregados));
        jTextField23.setText(String.valueOf(ladrilloM));
        jTextField24.setText(String.valueOf(ladrilloP));
        jTextField26.setText(String.valueOf(aceroC));
        jTextField25.setText(String.valueOf(formaleta));
        jTextField33.setText(String.valueOf(perdidacemento));
        jTextField34.setText(String.valueOf(perdidaagregados));
        jTextField35.setText(String.valueOf(perdidaladrilloM));
        jTextField36.setText(String.valueOf(perdidaladrilloP));
        jTextField37.setText(String.valueOf(perdidaaceroC));
        jTextField38.setText(String.valueOf(perdidaformaleta));
        jTextField46.setText(String.valueOf(pcn));
        jTextField47.setText(String.valueOf(pan));
        jTextField48.setText(String.valueOf(plmn));
        jTextField49.setText(String.valueOf(plpn));
        jTextField50.setText(String.valueOf(pacn));
        jTextField39.setText(String.valueOf(pfn));
        jButton3.setEnabled(false);
        Object[][] a =new Object[15][6];
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            a,  new String [] {
                "X1", "X2", "X3", "X4", "X5", "X6"
            }
                
                
        )
        
        {
            Class[] types = new Class [] {
                java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        jScrollPane1.setViewportView(jTable1);
        pausar=0;
    }
    
    
    public void colocarValor(float[][] matriz){
        //jTable1.setValueAt(valor,i,j);
        
        for(int i=0;i<15;i++){
            for(int j=0;j<6;j++){
                jTable1.setValueAt(matriz[i][j], i, j);
            }
        }
    }
    
    public void colocarDatosDias(float[] vector){
        //jTable1.setValueAt(valor,i,j);
        if(vector[0]>pcn){
            jTextField40.setText(String.valueOf(pcn));
            jTextField27.setText(String.valueOf(perdidacemento));
        }else{
            jTextField40.setText(String.valueOf(vector[0]));
            jTextField27.setText(String.valueOf((int)vector[0]*cemento/100));
        }
        
        if(vector[1]>pan){
            jTextField41.setText(String.valueOf(pan));
            jTextField28.setText(String.valueOf(perdidaagregados));
        }else{
            jTextField41.setText(String.valueOf(vector[1]));
            jTextField28.setText(String.valueOf((int)vector[1]*agregados/100));
        }
        
        if(vector[2]>plmn){
            jTextField42.setText(String.valueOf(plmn));
            jTextField29.setText(String.valueOf(perdidaladrilloM));
        }else{
            jTextField42.setText(String.valueOf(vector[2]));
            jTextField29.setText(String.valueOf((int)vector[2]*ladrilloM/100));
        }
        
        if(vector[3]>plpn){
            jTextField43.setText(String.valueOf(plpn));
            jTextField30.setText(String.valueOf(perdidaladrilloP));
        }else{
            jTextField43.setText(String.valueOf(vector[3]));
            jTextField30.setText(String.valueOf((int)vector[3]*ladrilloP/100));
        }
        
        if(vector[4]>pacn){
            jTextField44.setText(String.valueOf(pacn));
            jTextField31.setText(String.valueOf(perdidaaceroC));
        }else{
            jTextField44.setText(String.valueOf(vector[4]));
            jTextField31.setText(String.valueOf((int)vector[4]*aceroC/100));
        }
        
        if(vector[5]>pfn){
            jTextField45.setText(String.valueOf(pfn));
            jTextField32.setText(String.valueOf(perdidaformaleta));
        }else{
            jTextField45.setText(String.valueOf(vector[5]));
            jTextField32.setText(String.valueOf((int)vector[5]*formaleta/100));
        }
        
        
        
        
    }
    
    public void mostrarResultados(){
        
        jFrame6.setSize(1200,330);     
        jFrame6.setLocationRelativeTo(null);
        jFrame6.setVisible(true);
        jTextField84.setText(String.valueOf(perdidacemento));
        jTextField81.setText(String.valueOf(perdidaagregados));
        jTextField82.setText(String.valueOf(perdidaladrilloM));
        jTextField80.setText(String.valueOf(perdidaladrilloP));
        jTextField83.setText(String.valueOf(perdidaaceroC));
        jTextField75.setText(String.valueOf(perdidaformaleta));
        jTextField77.setText(String.valueOf(pcn));
        jTextField86.setText(String.valueOf(pan));
        jTextField79.setText(String.valueOf(plmn));
        jTextField78.setText(String.valueOf(plpn));
        jTextField76.setText(String.valueOf(pacn));
        jTextField85.setText(String.valueOf(pfn));
    }
   
    
       
    

}
